---
development:
  cloud_name: milestudios
  api_key: '429938831759714'
  api_secret: bzou02OT_vYvlEGrwCGd4jbmolc
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: milestudios
  api_key: '429938831759714'
  api_secret: bzou02OT_vYvlEGrwCGd4jbmolc
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: milestudios
  api_key: '429938831759714'
  api_secret: bzou02OT_vYvlEGrwCGd4jbmolc
  enhance_image_tag: true
  static_image_support: false
